### ISSUE TITLE
Sort fields list when returned

### ISSUE THREAD

**Issue by colemanm** [fulcrumapp/fulcrum-zapier#3]
When querying an app's available fields for filtering and action settings, the list should be sorted alphabetically.

![sort list](https://cldup.com/SddThNw0l6.png)

**Comment by colemanm** [comment]
Did we determine this isn't worth doing? Will close, if so... @zhm

**Comment by zhm** [comment]
I don't think it's possible. We'd have to ask someone at Zapier

**Comment by colemanm** [comment]
Not possible currently. Closing.
